"""Post-CIO guard checks.

The CIO memo is generated by an LLM and is therefore untrusted. ``guards.py``
runs after the CIO finishes and before the memo is published to
``examples/``. It enforces:

1. **Hard rules from contracts.CIOMemo** — re-validates the embedded JSON
   block. ``CIOMemo``'s pydantic validators already enforce ``no edge ⇒
   NO_ACTION`` and ``NO_ACTION ⇒ no sizing``; this just surfaces the failure
   cleanly.

2. **Risk Officer veto honored** — if ``risk.veto_reasons`` is non-empty, the
   CIO's recommendation MUST be ``NO_ACTION``.

3. **Risk Officer sizing band respected** — ``position_size_pct`` may not
   exceed the upper bound of the recommended sizing band.

4. **Vague-edge scan on the prose** — phrases like "brand strength" or
   "quality compounder" without a quantitative anchor in the same sentence
   are blocked (the CIO must justify with numbers, not narratives). A
   recommendation of ``NO_ACTION`` is exempt from the prose scan because the
   memo is explaining *why we are not acting*.

CLI
---
``python -m stonk_sage.guards check --run-dir data/runs/AAPL_2024-06-01_abc12345``

Exit code 0 on PASS, 1 on FAIL; reasons printed to stdout.
"""

from __future__ import annotations

import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path
from typing import Iterable

from pydantic import ValidationError

from stonk_sage.contracts import CIOMemo, RiskAssessment, SizingBand

__all__ = [
    "GuardCheckResult",
    "SIZING_CAP_PCT",
    "VAGUE_PHRASES",
    "extract_cio_json_block",
    "load_cio_markdown",
    "load_risk_assessment",
    "scan_vague_edges",
    "check_run_dir",
]


# ---------------------------------------------------------------------------
# Sizing band caps — kept in sync with risk-portfolio.instructions.md.
# ---------------------------------------------------------------------------

SIZING_CAP_PCT: dict[SizingBand, float] = {
    "NONE": 0.0,
    "STARTER_1_PCT": 1.0,
    "STANDARD_3_PCT": 3.0,
    "OVERWEIGHT_5_PCT": 5.0,
}


# ---------------------------------------------------------------------------
# Vague-edge denylist + quantitative anchor regex.
#
# Phrasing comes from common LLM hand-waving patterns. The anchor regex
# REQUIRES a unit on numbers — bare digits like "Apple opened 2 new stores"
# do not count as a quantitative anchor for "brand strength", per
# absol-stonk-sage-review. Anchors:
#   * digit + financial unit (% / bps / x / bn / m / k / pp)
#   * $-prefixed amount or $-prefixed ticker
#   * SEC filing forms (10-K, 10-Q, 8-K)
#   * fiscal-period references (FY24, Q1..Q4)
# ---------------------------------------------------------------------------

VAGUE_PHRASES: tuple[str, ...] = (
    "brand strength",
    "quality compounder",
    "ai opportunity",
    "secular growth",
    "strong management",
    "market leader",
    "defensive moat",
    "network effects",
    "pricing power",
    "category leader",
)

_QUANT_ANCHOR = re.compile(
    r"\d+(?:\.\d+)?\s*(?:%|bps|bp|x|bn|mn|pp|pts)\b"
    r"|\$\d"
    r"|\$[A-Z]{2,5}\b"
    r"|\bFY\d"
    r"|\bQ\d"
    r"|\b10-?[KQ]\b"
    r"|\b8-?K\b",
    re.IGNORECASE,
)


# ---------------------------------------------------------------------------
# Result type.
# ---------------------------------------------------------------------------


@dataclass
class GuardCheckResult:
    """Outcome of a guard run."""

    passed: bool
    failures: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def __bool__(self) -> bool:
        return self.passed

    def render(self) -> str:
        verdict = "PASS ✅" if self.passed else "FAIL ❌"
        lines = [f"guards: {verdict}"]
        for f in self.failures:
            lines.append(f"  ❌ {f}")
        for w in self.warnings:
            lines.append(f"  ⚠️  {w}")
        return "\n".join(lines)


# ---------------------------------------------------------------------------
# Loaders.
# ---------------------------------------------------------------------------


_FENCED_JSON = re.compile(r"```json\s*(\{.*?\})\s*```", re.DOTALL)


def extract_cio_json_block(markdown: str) -> dict:
    """Parse the first fenced ```json``` block in the CIO memo."""
    m = _FENCED_JSON.search(markdown)
    if not m:
        raise ValueError("CIO memo contains no fenced ```json``` block")
    return json.loads(m.group(1))


def load_cio_markdown(run_dir: Path) -> str:
    path = run_dir / "cio_draft.md"
    if not path.is_file():
        raise FileNotFoundError(f"Missing CIO draft at {path}")
    return path.read_text(encoding="utf-8")


def load_risk_assessment(run_dir: Path) -> RiskAssessment:
    path = run_dir / "risk.json"
    if not path.is_file():
        raise FileNotFoundError(f"Missing risk assessment at {path}")
    raw = path.read_text(encoding="utf-8")
    # risk.json may itself contain a fenced ```json``` block if captured verbatim.
    m = _FENCED_JSON.search(raw)
    payload = m.group(1) if m else raw
    return RiskAssessment.model_validate_json(payload)


# ---------------------------------------------------------------------------
# Vague-edge scanner.
# ---------------------------------------------------------------------------


def _split_sentences(prose: str) -> Iterable[str]:
    """Coarse sentence split for the vague-edge scan.

    Markdown headings (lines starting with ``#``) are structural metadata —
    they're stripped before splitting so a heading like
    ``# Investment Memo — AAPL as of 2024-06-01`` does not count as a
    quantitative anchor on behalf of the analytical prose.

    Splits on period / exclamation / question, plus line breaks, so a bullet
    list like ``- pricing power drove FY24 320bps`` is treated as one chunk.
    """
    non_heading_lines = [
        line for line in prose.splitlines() if not line.lstrip().startswith("#")
    ]
    cleaned = "\n".join(non_heading_lines)
    parts = re.split(r"(?<=[.!?])\s+|\n+", cleaned)
    for p in parts:
        s = p.strip(" \t-*•")
        if s:
            yield s


def scan_vague_edges(prose: str) -> list[str]:
    """Return a list of offending sentences from the CIO memo prose.

    Rule:
        (vague phrase present AND no quantitative anchor in same sentence)
        OR (no quantitative anchor at all in any sentence)
        → vague
    """
    offenses: list[str] = []
    any_anchor = False
    for sentence in _split_sentences(prose):
        lower = sentence.lower()
        has_anchor = bool(_QUANT_ANCHOR.search(sentence))
        any_anchor = any_anchor or has_anchor
        hit_phrase = next((p for p in VAGUE_PHRASES if p in lower), None)
        if hit_phrase and not has_anchor:
            offenses.append(f"'{hit_phrase}' without quant anchor in: {sentence!r}")
    if not any_anchor:
        offenses.append("No quantitative anchor found anywhere in the prose")
    return offenses


# ---------------------------------------------------------------------------
# Cross-checks (CIO vs Risk).
# ---------------------------------------------------------------------------


def _strip_cio_json_block(markdown: str) -> str:
    """Remove the fenced JSON block so vague-edge scan runs on prose only."""
    return _FENCED_JSON.sub("", markdown, count=1)


def _check_risk_alignment(memo: CIOMemo, risk: RiskAssessment) -> list[str]:
    failures: list[str] = []
    if risk.veto_reasons:
        # When the Risk Officer vetoes, the only thing we care about is that
        # the CIO honored the veto. Sizing-band failures downstream are a
        # mechanical consequence and would just spam render() output.
        if memo.recommendation != "NO_ACTION":
            failures.append(
                f"Risk Officer issued a veto ({risk.veto_reasons!r}) but CIO "
                f"recommendation is {memo.recommendation!r}; must be 'NO_ACTION'"
            )
        return failures
    cap = SIZING_CAP_PCT[risk.recommended_sizing_band]
    if memo.position_size_pct is not None and memo.position_size_pct > cap:
        failures.append(
            f"position_size_pct={memo.position_size_pct} exceeds Risk Officer "
            f"band {risk.recommended_sizing_band!r} cap of {cap}%"
        )
    if risk.recommended_sizing_band == "NONE" and memo.position_size_pct not in (None, 0.0):
        failures.append(
            "Risk Officer banded NONE; position_size_pct must be null or 0.0"
        )
    return failures


# ---------------------------------------------------------------------------
# Top-level guard.
# ---------------------------------------------------------------------------


def check_run_dir(run_dir: Path) -> GuardCheckResult:
    """Run all guards on a staged committee run directory."""
    result = GuardCheckResult(passed=True)
    try:
        markdown = load_cio_markdown(run_dir)
    except FileNotFoundError as exc:
        result.passed = False
        result.failures.append(str(exc))
        return result

    try:
        payload = extract_cio_json_block(markdown)
    except (ValueError, json.JSONDecodeError) as exc:
        result.passed = False
        result.failures.append(f"CIO JSON block invalid: {exc}")
        return result

    try:
        memo = CIOMemo.model_validate(payload)
    except ValidationError as exc:
        result.passed = False
        result.failures.append(f"CIOMemo failed contract validation: {exc}")
        return result

    try:
        risk = load_risk_assessment(run_dir)
    except (FileNotFoundError, ValidationError, json.JSONDecodeError) as exc:
        result.passed = False
        result.failures.append(f"Risk assessment unreadable: {exc}")
        return result

    risk_failures = _check_risk_alignment(memo, risk)
    if risk_failures:
        result.failures.extend(risk_failures)

    if memo.recommendation != "NO_ACTION":
        prose = _strip_cio_json_block(markdown)
        vague = scan_vague_edges(prose)
        if vague:
            result.failures.extend(f"vague edge: {v}" for v in vague)

    result.passed = not result.failures
    return result


# ---------------------------------------------------------------------------
# CLI.
# ---------------------------------------------------------------------------


def _cli(argv: list[str] | None = None) -> int:
    import argparse

    parser = argparse.ArgumentParser(prog="stonk_sage.guards")
    sub = parser.add_subparsers(dest="cmd", required=True)

    chk = sub.add_parser("check", help="Run guards on a staged run directory.")
    chk.add_argument("--run-dir", required=True, type=Path)

    args = parser.parse_args(argv)
    if args.cmd == "check":
        result = check_run_dir(args.run_dir)
        print(result.render())
        return 0 if result.passed else 1
    return 1


if __name__ == "__main__":
    sys.exit(_cli())
